USE cms;
SET NAMES 'UTF8';
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS nav;
DROP TABLE IF EXISTS article;
DROP TABLE IF EXISTS _comment;
DROP TABLE IF EXISTS basic;

CREATE TABLE IF NOT EXISTS user(
    id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password CHAR(40) NOT NULL,
    realname VARCHAR(20) NOT NULL DEFAULT 'FIREUP',
    last_login_time DATETIME NOT NULL
)DEFAULT CHARSET=UTF8;

INSERT INTO user(username,password,realname,last_login_time) VALUES('admin', sha1('admin'),'薛文聪',NOW());

CREATE TABLE IF NOT EXISTS menu(
    menu_id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    menu_name VARCHAR(6) NOT NULL,
    menu_pid SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    menu_status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    menu_order SMALLINT UNSIGNED NOT NULL
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS article(
    a_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    a_catid SMALLINT NOT NULL,
    a_title VARCHAR(50) NOT NULL,
    a_status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    a_copy_from VARCHAR(10) NOT NULL DEFAULT '本站',
    a_create_time DATETIME NOT NULL,
    a_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    a_cont TEXT NOT NULL
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS _comment(
    c_id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    c_nickname VARCHAR(20) NOT NULL DEFAULT '匿名',
    c_cont VARCHAR(140) NOT NULL,
    c_time DATETIME NOT NULL,
    c_a_id INT UNSIGNED NOT NULL
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS basic(
    web_title VARCHAR(12) NOT NULL,
    web_keywords VARCHAR(30) NOT NULL,
    web_desc VARCHAR(50) NOT NULL,
    web_today_login SMALLINT UNSIGNED NOT NULL
)DEFAULT CHARSET=UTF8;

INSERT INTO basic VALUES ('fireupCMS', 'fireupcms  资讯 体育 新闻 科技', 'fireupcms资讯网是提供最新的体育等栏目的新闻网站',0);

--mysql定时任务,用于更新每日登录人数
SET time_zone='+8:00';
SET GLOBAL event_scheduler=ON;
DROP EVENT IF EXISTS update_today_login;

DELIMITER $$
CREATE EVENT update_today_login
ON SCHEDULE EVERY 1 DAY STARTS TIMESTAMP '2017-05-24 00:00:00'
DO
BEGIN
UPDATE basic SET web_today_login=0;
END
$$

DELIMITER ;
